[package]
name = "melange-protocol"
version = "0.1.0"
authors = ["Melange Network"]
edition = "2018"
description = "Common helpers for melange-protocol"
license = ""
repository = "https://github.com/melange-protocol/melange-contracts"
homepage = "https://melange.finance"
documentation = "https://docs.melange.finance"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "1.0.0" }
cosmwasm-std = { version = "1.1.9" }
cosmwasm-storage = { version = "1.1.9" }
sei-cosmwasm = { version = "0.4.9" }
terraswap = { version = "2.8.0" }
schemars = "0.8.11"
serde = { version = "1.0.150", default-features = false, features = ["derive"] }
uint = { version = "0.9.5" }

[profile.release]
overflow-checks = true
